//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pvp.Core.MediaEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pvp.Core.MediaEngine.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Parental Level Change Request to level {0}?.
        /// </summary>
        internal static string accept_parental_level_format {
            get {
                return ResourceManager.GetString("accept_parental_level_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio stream.
        /// </summary>
        internal static string dvd_audio_stream {
            get {
                return ResourceManager.GetString("dvd_audio_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not render the DVD volume..
        /// </summary>
        internal static string dvd_cant_render_volume {
            get {
                return ResourceManager.GetString("dvd_cant_render_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} DVD-Video streams failed to render properly.
        /// </summary>
        internal static string dvd_failed_streams_format {
            get {
                return ResourceManager.GetString("dvd_failed_streams_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the application cannot run using the current DirectShow components..
        /// </summary>
        internal static string dvd_incompatible_dshow {
            get {
                return ResourceManager.GetString("dvd_incompatible_dshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified DVD-Video volume was invalid.
        /// </summary>
        internal static string dvd_invalid_volume {
            get {
                return ResourceManager.GetString("dvd_invalid_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video decoder doesn&apos;t produce closed captioning data.
        /// </summary>
        internal static string dvd_no_line21in {
            get {
                return ResourceManager.GetString("dvd_no_line21in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded closed caption data not rendered properly.
        /// </summary>
        internal static string dvd_no_line21out {
            get {
                return ResourceManager.GetString("dvd_no_line21out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough decoders to decode all streams..
        /// </summary>
        internal static string dvd_not_enough_decoders {
            get {
                return ResourceManager.GetString("dvd_not_enough_decoders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string dvd_question_continue {
            get {
                return ResourceManager.GetString("dvd_question_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subpicture stream.
        /// </summary>
        internal static string dvd_subpicture_stream {
            get {
                return ResourceManager.GetString("dvd_subpicture_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred!.
        /// </summary>
        internal static string dvd_unknown_error {
            get {
                return ResourceManager.GetString("dvd_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid DVD-Video volume could be located.
        /// </summary>
        internal static string dvd_unknown_volume {
            get {
                return ResourceManager.GetString("dvd_unknown_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video stream.
        /// </summary>
        internal static string dvd_video_stream {
            get {
                return ResourceManager.GetString("dvd_video_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the DirectSound filter to the Graph..
        /// </summary>
        internal static string error_cant_add_ds {
            get {
                return ResourceManager.GetString("error_cant_add_ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the Enhanced Video Renderer to the Graph..
        /// </summary>
        internal static string error_cant_add_evr {
            get {
                return ResourceManager.GetString("error_cant_add_evr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the VMR to the Graph..
        /// </summary>
        internal static string error_cant_add_vmr {
            get {
                return ResourceManager.GetString("error_cant_add_vmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the VMR9 to the Graph..
        /// </summary>
        internal static string error_cant_add_vmr9 {
            get {
                return ResourceManager.GetString("error_cant_add_vmr9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the Video Renderer filter to the Graph..
        /// </summary>
        internal static string error_cant_add_vr {
            get {
                return ResourceManager.GetString("error_cant_add_vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not configure the Enhanced Video Renderer..
        /// </summary>
        internal static string error_cant_configure_evr {
            get {
                return ResourceManager.GetString("error_cant_configure_evr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not configure the VMR..
        /// </summary>
        internal static string error_cant_configure_vmr {
            get {
                return ResourceManager.GetString("error_cant_configure_vmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not configure the VMR9..
        /// </summary>
        internal static string error_cant_configure_vmr9 {
            get {
                return ResourceManager.GetString("error_cant_configure_vmr9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of the DirectSound filter..
        /// </summary>
        internal static string error_cant_create_ds {
            get {
                return ResourceManager.GetString("error_cant_create_ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the DVD Graph Builder..
        /// </summary>
        internal static string error_cant_create_dvd_builder {
            get {
                return ResourceManager.GetString("error_cant_create_dvd_builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the Filter Graph Manager..
        /// </summary>
        internal static string error_cant_create_fgm {
            get {
                return ResourceManager.GetString("error_cant_create_fgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create media window..
        /// </summary>
        internal static string error_cant_create_media_window {
            get {
                return ResourceManager.GetString("error_cant_create_media_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of the Video Renderer filter..
        /// </summary>
        internal static string error_cant_create_vr {
            get {
                return ResourceManager.GetString("error_cant_create_vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the video dimension..
        /// </summary>
        internal static string error_cant_get_video_size {
            get {
                return ResourceManager.GetString("error_cant_get_video_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t play this disc..
        /// </summary>
        internal static string error_cant_play_disc {
            get {
                return ResourceManager.GetString("error_cant_play_disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t play this file..
        /// </summary>
        internal static string error_cant_play_file {
            get {
                return ResourceManager.GetString("error_cant_play_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t render this file..
        /// </summary>
        internal static string error_cant_render_file {
            get {
                return ResourceManager.GetString("error_cant_render_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve all necessary Filter Graph Manager&apos;s interfaces..
        /// </summary>
        internal static string error_cant_retrieve_all_interfaces {
            get {
                return ResourceManager.GetString("error_cant_retrieve_all_interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HWND provided..
        /// </summary>
        internal static string error_no_hwnd {
            get {
                return ResourceManager.GetString("error_no_hwnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a source filter for this file..
        /// </summary>
        internal static string error_no_source_filter {
            get {
                return ResourceManager.GetString("error_no_source_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file may not be a video file. Do you want to open it anyway?.
        /// </summary>
        internal static string fgb_question_open_anyway {
            get {
                return ResourceManager.GetString("fgb_question_open_anyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIFF.
        /// </summary>
        internal static string mi_aiff {
            get {
                return ResourceManager.GetString("mi_aiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Systems Format (ASF).
        /// </summary>
        internal static string mi_asf {
            get {
                return ResourceManager.GetString("mi_asf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU.
        /// </summary>
        internal static string mi_au {
            get {
                return ResourceManager.GetString("mi_au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVI.
        /// </summary>
        internal static string mi_avi {
            get {
                return ResourceManager.GetString("mi_avi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dss Audio.
        /// </summary>
        internal static string mi_dss_audio {
            get {
                return ResourceManager.GetString("mi_dss_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dss Video.
        /// </summary>
        internal static string mi_dss_video {
            get {
                return ResourceManager.GetString("mi_dss_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD disc.
        /// </summary>
        internal static string mi_dvd_disc {
            get {
                return ResourceManager.GetString("mi_dvd_disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG1 audio.
        /// </summary>
        internal static string mi_mpeg1_audio {
            get {
                return ResourceManager.GetString("mi_mpeg1_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG1 system.
        /// </summary>
        internal static string mi_mpeg1_system {
            get {
                return ResourceManager.GetString("mi_mpeg1_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG1 video.
        /// </summary>
        internal static string mi_mpeg1_video {
            get {
                return ResourceManager.GetString("mi_mpeg1_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG1 video CD.
        /// </summary>
        internal static string mi_mpeg1_video_cd {
            get {
                return ResourceManager.GetString("mi_mpeg1_video_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV.
        /// </summary>
        internal static string mi_wav {
            get {
                return ResourceManager.GetString("mi_wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Change?.
        /// </summary>
        internal static string mw_accept_change_question {
            get {
                return ResourceManager.GetString("mw_accept_change_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Parental Level Change Request to level {0}?.
        /// </summary>
        internal static string mw_accept_parental_level_format {
            get {
                return ResourceManager.GetString("mw_accept_parental_level_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key exchange for DVD copy protection failed.\nCan&apos;t playback this DVD-Video disc..
        /// </summary>
        internal static string mw_dvd_copyprotect_failed {
            get {
                return ResourceManager.GetString("mw_dvd_copyprotect_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DVD-Video disc cannot be played on this system, because it is\nnot authored to be played in the installed decoder&apos;s region..
        /// </summary>
        internal static string mw_dvd_disc_decoder_regions {
            get {
                return ResourceManager.GetString("mw_dvd_disc_decoder_regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DVD-Video disc is incorrectly authored for v1.0 of the spec.\nCan&apos;t playback this disc..
        /// </summary>
        internal static string mw_dvd_invalid_disc {
            get {
                return ResourceManager.GetString("mw_dvd_invalid_disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DVD-Video disc cannot be played, because it is not\nauthored to play in the current system region.\nThe region mismatch may be fixed by changing the\nsystem region..
        /// </summary>
        internal static string mw_dvd_invalid_region {
            get {
                return ResourceManager.GetString("mw_dvd_invalid_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player parental level is set lower than the lowest parental\nlevel available in this DVD-Video content.\nCannot playback this DVD-Video disc..
        /// </summary>
        internal static string mw_dvd_low_parental_level {
            get {
                return ResourceManager.GetString("mw_dvd_low_parental_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DVD-Video content is protected by Macrovision.\nThe system does not satisfy Macrovision requirement.\nCan&apos;t continue playing this disc..
        /// </summary>
        internal static string mw_dvd_macrovision_error {
            get {
                return ResourceManager.GetString("mw_dvd_macrovision_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No DVD-Video disc can be played on this system, because \nthe system region does not match the decoder region.\nPlease contact the manufacturer of this system..
        /// </summary>
        internal static string mw_dvd_system_decoder_regions {
            get {
                return ResourceManager.GetString("mw_dvd_system_decoder_regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error (possibly incorrectly authored content)\nwas encountered.\nCan&apos;t playback this DVD-Video disc..
        /// </summary>
        internal static string mw_dvd_unexpected_error {
            get {
                return ResourceManager.GetString("mw_dvd_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file on the DVD disc could not be opened. Playback may not continue..
        /// </summary>
        internal static string mw_dvd_warning_cant_open_file {
            get {
                return ResourceManager.GetString("mw_dvd_warning_cant_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read part of a file on the DVD disc. Playback may not continue..
        /// </summary>
        internal static string mw_dvd_warning_cant_read {
            get {
                return ResourceManager.GetString("mw_dvd_warning_cant_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not move to a different part of a file on the DVD disc. Playback may not continue..
        /// </summary>
        internal static string mw_dvd_warning_cant_seek {
            get {
                return ResourceManager.GetString("mw_dvd_warning_cant_seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string mw_error_occured {
            get {
                return ResourceManager.GetString("mw_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The play is aborted..
        /// </summary>
        internal static string mw_play_aborted {
            get {
                return ResourceManager.GetString("mw_play_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream {0}.
        /// </summary>
        internal static string mw_stream_format {
            get {
                return ResourceManager.GetString("mw_stream_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string si_audio {
            get {
                return ResourceManager.GetString("si_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte stream with no time stamps.
        /// </summary>
        internal static string si_byte_stream {
            get {
                return ResourceManager.GetString("si_byte_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interleaved audio and video.
        /// </summary>
        internal static string si_interleaved_audio_and_video {
            get {
                return ResourceManager.GetString("si_interleaved_audio_and_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 21 data.
        /// </summary>
        internal static string si_line21data {
            get {
                return ResourceManager.GetString("si_line21data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI.
        /// </summary>
        internal static string si_midi {
            get {
                return ResourceManager.GetString("si_midi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script command.
        /// </summary>
        internal static string si_script_command {
            get {
                return ResourceManager.GetString("si_script_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string si_text {
            get {
                return ResourceManager.GetString("si_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timecode data.
        /// </summary>
        internal static string si_timecode {
            get {
                return ResourceManager.GetString("si_timecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized compression type.
        /// </summary>
        internal static string si_unknown_compression_type {
            get {
                return ResourceManager.GetString("si_unknown_compression_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string si_video {
            get {
                return ResourceManager.GetString("si_video", resourceCulture);
            }
        }
    }
}
