//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pvp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pvp.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2004-2010 - Andrei Dzimchuk.
        /// </summary>
        internal static string about_copyright {
            get {
                return ResourceManager.GetString("about_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is licensed under Ms-PL..
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PVP.
        /// </summary>
        internal static string about_pvp {
            get {
                return ResourceManager.GetString("about_pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .3g2 - 3GPP2.
        /// </summary>
        internal static string file_type_3g2 {
            get {
                return ResourceManager.GetString("file_type_3g2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .3gp - 3GPP.
        /// </summary>
        internal static string file_type_3gp {
            get {
                return ResourceManager.GetString("file_type_3gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .asf - Advanced Streaming Format.
        /// </summary>
        internal static string file_type_asf {
            get {
                return ResourceManager.GetString("file_type_asf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .avi - Audio-Video Interleaved.
        /// </summary>
        internal static string file_type_avi {
            get {
                return ResourceManager.GetString("file_type_avi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dat - MPEG movie on VCD or SVCD.
        /// </summary>
        internal static string file_type_dat {
            get {
                return ResourceManager.GetString("file_type_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .divx - Avi file compressed with DivX codec.
        /// </summary>
        internal static string file_type_divx {
            get {
                return ResourceManager.GetString("file_type_divx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .flv - Flash Video.
        /// </summary>
        internal static string file_type_flv {
            get {
                return ResourceManager.GetString("file_type_flv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ifo - DVD file.
        /// </summary>
        internal static string file_type_ifo {
            get {
                return ResourceManager.GetString("file_type_ifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .m1v - MPEG1 video only.
        /// </summary>
        internal static string file_type_m1v {
            get {
                return ResourceManager.GetString("file_type_m1v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .m2v - MPEG2 video only.
        /// </summary>
        internal static string file_type_m2v {
            get {
                return ResourceManager.GetString("file_type_m2v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mkv - Matroska video.
        /// </summary>
        internal static string file_type_mkv {
            get {
                return ResourceManager.GetString("file_type_mkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mov - QuickTime movie.
        /// </summary>
        internal static string file_type_mov {
            get {
                return ResourceManager.GetString("file_type_mov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mp4 - MPEG4.
        /// </summary>
        internal static string file_type_mp4 {
            get {
                return ResourceManager.GetString("file_type_mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpe - Motion Picture Experts Group.
        /// </summary>
        internal static string file_type_mpe {
            get {
                return ResourceManager.GetString("file_type_mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpeg - Motion Picture Experts Group.
        /// </summary>
        internal static string file_type_mpeg {
            get {
                return ResourceManager.GetString("file_type_mpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpg - Motion Picture Experts Group.
        /// </summary>
        internal static string file_type_mpg {
            get {
                return ResourceManager.GetString("file_type_mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .qt - QuickTime movie.
        /// </summary>
        internal static string file_type_qt {
            get {
                return ResourceManager.GetString("file_type_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vob - Video Object.
        /// </summary>
        internal static string file_type_vob {
            get {
                return ResourceManager.GetString("file_type_vob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .wmv - Windows Media Video.
        /// </summary>
        internal static string file_type_wmv {
            get {
                return ResourceManager.GetString("file_type_wmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string infodialog_Aspect_Ratio {
            get {
                return ResourceManager.GetString("infodialog_Aspect_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate.
        /// </summary>
        internal static string infodialog_Bit_Rate {
            get {
                return ResourceManager.GetString("infodialog_Bit_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kbit/s.
        /// </summary>
        internal static string infodialog_bitrate_value_format {
            get {
                return ResourceManager.GetString("infodialog_bitrate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} bits per sample.
        /// </summary>
        internal static string infodialog_bits_per_sample_format {
            get {
                return ResourceManager.GetString("infodialog_bits_per_sample_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} channel.
        /// </summary>
        internal static string infodialog_channel_format {
            get {
                return ResourceManager.GetString("infodialog_channel_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} channels.
        /// </summary>
        internal static string infodialog_channels_format {
            get {
                return ResourceManager.GetString("infodialog_channels_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Chapter.
        /// </summary>
        internal static string infodialog_Current_Chapter {
            get {
                return ResourceManager.GetString("infodialog_Current_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Domain.
        /// </summary>
        internal static string infodialog_Current_Domain {
            get {
                return ResourceManager.GetString("infodialog_Current_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Title.
        /// </summary>
        internal static string infodialog_Current_Title {
            get {
                return ResourceManager.GetString("infodialog_Current_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string infodialog_duration {
            get {
                return ResourceManager.GetString("infodialog_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        internal static string infodialog_dvd_frequency_value_format {
            get {
                return ResourceManager.GetString("infodialog_dvd_frequency_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstPlay.
        /// </summary>
        internal static string infodialog_dvddomain_FirstPlay {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_FirstPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string infodialog_dvddomain_Stop {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string infodialog_dvddomain_Title {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoManagerMenu.
        /// </summary>
        internal static string infodialog_dvddomain_VideoManagerMenu {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_VideoManagerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoTitleSetMenu.
        /// </summary>
        internal static string infodialog_dvddomain_VideoTitleSetMenu {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_VideoTitleSetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string infodialog_Format {
            get {
                return ResourceManager.GetString("infodialog_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Type.
        /// </summary>
        internal static string infodialog_Format_Type {
            get {
                return ResourceManager.GetString("infodialog_Format_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Rate.
        /// </summary>
        internal static string infodialog_Frame_Rate {
            get {
                return ResourceManager.GetString("infodialog_Frame_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f3} Hz.
        /// </summary>
        internal static string infodialog_framerate_value_format {
            get {
                return ResourceManager.GetString("infodialog_framerate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlace Mode.
        /// </summary>
        internal static string infodialog_Interlace_Mode {
            get {
                return ResourceManager.GetString("infodialog_Interlace_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string infodialog_Language {
            get {
                return ResourceManager.GetString("infodialog_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Source.
        /// </summary>
        internal static string infodialog_media_source {
            get {
                return ResourceManager.GetString("infodialog_media_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        internal static string infodialog_samplerate_value_format {
            get {
                return ResourceManager.GetString("infodialog_samplerate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Duration.
        /// </summary>
        internal static string infodialog_Title_Duration {
            get {
                return ResourceManager.GetString("infodialog_Title_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV System.
        /// </summary>
        internal static string infodialog_TV_System {
            get {
                return ResourceManager.GetString("infodialog_TV_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} Hz.
        /// </summary>
        internal static string infodialog_tv_system_value_format {
            get {
                return ResourceManager.GetString("infodialog_tv_system_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type/Format.
        /// </summary>
        internal static string infodialog_type_format {
            get {
                return ResourceManager.GetString("infodialog_type_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format.
        /// </summary>
        internal static string infodialog_Video_Format {
            get {
                return ResourceManager.GetString("infodialog_Video_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        internal static string infodialog_Video_Size {
            get {
                return ResourceManager.GetString("infodialog_Video_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream {0}.
        /// </summary>
        internal static string infofialog_Stream_format {
            get {
                return ResourceManager.GetString("infofialog_Stream_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string keys_about {
            get {
                return ResourceManager.GetString("keys_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string keys_app {
            get {
                return ResourceManager.GetString("keys_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        internal static string keys_ar_16_9 {
            get {
                return ResourceManager.GetString("keys_ar_16_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:3.
        /// </summary>
        internal static string keys_ar_4_3 {
            get {
                return ResourceManager.GetString("keys_ar_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47:20.
        /// </summary>
        internal static string keys_ar_47_20 {
            get {
                return ResourceManager.GetString("keys_ar_47_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string keys_ar_free {
            get {
                return ResourceManager.GetString("keys_ar_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Original.
        /// </summary>
        internal static string keys_ar_original {
            get {
                return ResourceManager.GetString("keys_ar_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string keys_aspect_ratio {
            get {
                return ResourceManager.GetString("keys_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string keys_backward {
            get {
                return ResourceManager.GetString("keys_backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        internal static string keys_close_file {
            get {
                return ResourceManager.GetString("keys_close_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string keys_exit {
            get {
                return ResourceManager.GetString("keys_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string keys_file {
            get {
                return ResourceManager.GetString("keys_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        internal static string keys_file_info {
            get {
                return ResourceManager.GetString("keys_file_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string keys_forward {
            get {
                return ResourceManager.GetString("keys_forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string keys_full_screen {
            get {
                return ResourceManager.GetString("keys_full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string keys_open_file {
            get {
                return ResourceManager.GetString("keys_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Play.
        /// </summary>
        internal static string keys_pause {
            get {
                return ResourceManager.GetString("keys_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string keys_play {
            get {
                return ResourceManager.GetString("keys_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string keys_playback {
            get {
                return ResourceManager.GetString("keys_playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string keys_pref {
            get {
                return ResourceManager.GetString("keys_pref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string keys_repeat {
            get {
                return ResourceManager.GetString("keys_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot.
        /// </summary>
        internal static string keys_screenshot {
            get {
                return ResourceManager.GetString("keys_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        internal static string keys_seek {
            get {
                return ResourceManager.GetString("keys_seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string keys_stop {
            get {
                return ResourceManager.GetString("keys_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        internal static string keys_video_size {
            get {
                return ResourceManager.GetString("keys_video_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string keys_video_size_100 {
            get {
                return ResourceManager.GetString("keys_video_size_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200%.
        /// </summary>
        internal static string keys_video_size_200 {
            get {
                return ResourceManager.GetString("keys_video_size_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        internal static string keys_video_size_50 {
            get {
                return ResourceManager.GetString("keys_video_size_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string keys_video_size_free {
            get {
                return ResourceManager.GetString("keys_video_size_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string keys_volume {
            get {
                return ResourceManager.GetString("keys_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string keys_volume_decrease {
            get {
                return ResourceManager.GetString("keys_volume_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string keys_volume_increase {
            get {
                return ResourceManager.GetString("keys_volume_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string keys_volume_mute {
            get {
                return ResourceManager.GetString("keys_volume_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string mi_about {
            get {
                return ResourceManager.GetString("mi_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle {0}.
        /// </summary>
        internal static string mi_angle_format {
            get {
                return ResourceManager.GetString("mi_angle_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Menu.
        /// </summary>
        internal static string mi_angle_menu {
            get {
                return ResourceManager.GetString("mi_angle_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing Angles.
        /// </summary>
        internal static string mi_angles {
            get {
                return ResourceManager.GetString("mi_angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string mi_app_lang {
            get {
                return ResourceManager.GetString("mi_app_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string mi_app_lang_default {
            get {
                return ResourceManager.GetString("mi_app_lang_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string mi_app_lang_russian {
            get {
                return ResourceManager.GetString("mi_app_lang_russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string mi_application {
            get {
                return ResourceManager.GetString("mi_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string mi_aspect_ratio {
            get {
                return ResourceManager.GetString("mi_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string mi_aspect_ratio_free {
            get {
                return ResourceManager.GetString("mi_aspect_ratio_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Original.
        /// </summary>
        internal static string mi_aspect_ratio_original {
            get {
                return ResourceManager.GetString("mi_aspect_ratio_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Menu.
        /// </summary>
        internal static string mi_audio_menu {
            get {
                return ResourceManager.GetString("mi_audio_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Streams.
        /// </summary>
        internal static string mi_audio_streams {
            get {
                return ResourceManager.GetString("mi_audio_streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter {0}.
        /// </summary>
        internal static string mi_chapter_format {
            get {
                return ResourceManager.GetString("mi_chapter_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Menu.
        /// </summary>
        internal static string mi_chapter_menu {
            get {
                return ResourceManager.GetString("mi_chapter_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Menu (Resume).
        /// </summary>
        internal static string mi_close_menu_resume {
            get {
                return ResourceManager.GetString("mi_close_menu_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Controlbar.
        /// </summary>
        internal static string mi_controlbar {
            get {
                return ResourceManager.GetString("mi_controlbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Subtitles.
        /// </summary>
        internal static string mi_display_subpictures {
            get {
                return ResourceManager.GetString("mi_display_subpictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string mi_exit {
            get {
                return ResourceManager.GetString("mi_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string mi_file {
            get {
                return ResourceManager.GetString("mi_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose.
        /// </summary>
        internal static string mi_file_close {
            get {
                return ResourceManager.GetString("mi_file_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Information.
        /// </summary>
        internal static string mi_file_information {
            get {
                return ResourceManager.GetString("mi_file_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string mi_file_open {
            get {
                return ResourceManager.GetString("mi_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play DVD.
        /// </summary>
        internal static string mi_file_play_dvd {
            get {
                return ResourceManager.GetString("mi_file_play_dvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string mi_filters {
            get {
                return ResourceManager.GetString("mi_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string mi_fullscreen {
            get {
                return ResourceManager.GetString("mi_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To....
        /// </summary>
        internal static string mi_goto_menu {
            get {
                return ResourceManager.GetString("mi_goto_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Languages.
        /// </summary>
        internal static string mi_menu_languages {
            get {
                return ResourceManager.GetString("mi_menu_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;ause.
        /// </summary>
        internal static string mi_pause {
            get {
                return ResourceManager.GetString("mi_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Play.
        /// </summary>
        internal static string mi_play {
            get {
                return ResourceManager.GetString("mi_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playrate.
        /// </summary>
        internal static string mi_playrate {
            get {
                return ResourceManager.GetString("mi_playrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Preferences.
        /// </summary>
        internal static string mi_preferences {
            get {
                return ResourceManager.GetString("mi_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string mi_repeat {
            get {
                return ResourceManager.GetString("mi_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Menu.
        /// </summary>
        internal static string mi_root_menu {
            get {
                return ResourceManager.GetString("mi_root_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Menu.
        /// </summary>
        internal static string mi_select_menu {
            get {
                return ResourceManager.GetString("mi_select_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stop.
        /// </summary>
        internal static string mi_stop {
            get {
                return ResourceManager.GetString("mi_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subpicture Menu.
        /// </summary>
        internal static string mi_subpicture_menu {
            get {
                return ResourceManager.GetString("mi_subpicture_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        internal static string mi_subpictures {
            get {
                return ResourceManager.GetString("mi_subpictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title {0}.
        /// </summary>
        internal static string mi_title_format {
            get {
                return ResourceManager.GetString("mi_title_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Menu.
        /// </summary>
        internal static string mi_title_menu {
            get {
                return ResourceManager.GetString("mi_title_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        internal static string mi_video_size {
            get {
                return ResourceManager.GetString("mi_video_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string mi_video_size_free {
            get {
                return ResourceManager.GetString("mi_video_size_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string mi_volume {
            get {
                return ResourceManager.GetString("mi_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string mi_volume_down {
            get {
                return ResourceManager.GetString("mi_volume_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string mi_volume_mute {
            get {
                return ResourceManager.GetString("mi_volume_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string mi_volume_up {
            get {
                return ResourceManager.GetString("mi_volume_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string preferred_filter_auto {
            get {
                return ResourceManager.GetString("preferred_filter_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful and convenient video player for Windows 2000, XP, Vista and 7. The player is capable to play most video formats (given the necessary decoders are present on the system) and provides full DVD support. In addition, it provides advanced functionality like configuration of preferred decoders and renderers..
        /// </summary>
        internal static string program_description {
            get {
                return ResourceManager.GetString("program_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Video Player.
        /// </summary>
        internal static string program_name {
            get {
                return ResourceManager.GetString("program_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have altered the &quot;System Tray&quot; option.{0}You need to restart the application for the changes to take effect..
        /// </summary>
        internal static string systray_warning_format {
            get {
                return ResourceManager.GetString("systray_warning_format", resourceCulture);
            }
        }
    }
}
