//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pvp.Theme.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pvp.Theme.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string captionbar_close {
            get {
                return ResourceManager.GetString("captionbar_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        internal static string captionbar_maximize {
            get {
                return ResourceManager.GetString("captionbar_maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string captionbar_minimize {
            get {
                return ResourceManager.GetString("captionbar_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string captionbar_restore {
            get {
                return ResourceManager.GetString("captionbar_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string controlbar_backward {
            get {
                return ResourceManager.GetString("controlbar_backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string controlbar_forward {
            get {
                return ResourceManager.GetString("controlbar_forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string controlbar_mute {
            get {
                return ResourceManager.GetString("controlbar_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string controlbar_pause {
            get {
                return ResourceManager.GetString("controlbar_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string controlbar_play {
            get {
                return ResourceManager.GetString("controlbar_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string controlbar_repeat {
            get {
                return ResourceManager.GetString("controlbar_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seekbar.
        /// </summary>
        internal static string controlbar_seekbar {
            get {
                return ResourceManager.GetString("controlbar_seekbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string controlbar_stop {
            get {
                return ResourceManager.GetString("controlbar_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the begining.
        /// </summary>
        internal static string controlbar_to_begining {
            get {
                return ResourceManager.GetString("controlbar_to_begining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the end.
        /// </summary>
        internal static string controlbar_to_end {
            get {
                return ResourceManager.GetString("controlbar_to_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string controlbar_volume {
            get {
                return ResourceManager.GetString("controlbar_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not defined..
        /// </summary>
        internal static string err_file_not_defined {
            get {
                return ResourceManager.GetString("err_file_not_defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource location is not defined..
        /// </summary>
        internal static string err_resource_loc_not_defined {
            get {
                return ResourceManager.GetString("err_resource_loc_not_defined", resourceCulture);
            }
        }
    }
}
