//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pvp.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pvp.App.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2004-2014 - Andrei Dzimchuk.
        /// </summary>
        public static string about_copyright {
            get {
                return ResourceManager.GetString("about_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is licensed under Ms-PL..
        /// </summary>
        public static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About PVP.
        /// </summary>
        public static string about_pvp {
            get {
                return ResourceManager.GetString("about_pvp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string captionbar_close {
            get {
                return ResourceManager.GetString("captionbar_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string captionbar_maximize {
            get {
                return ResourceManager.GetString("captionbar_maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string captionbar_minimize {
            get {
                return ResourceManager.GetString("captionbar_minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string captionbar_restore {
            get {
                return ResourceManager.GetString("captionbar_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string controlbar_backward {
            get {
                return ResourceManager.GetString("controlbar_backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string controlbar_forward {
            get {
                return ResourceManager.GetString("controlbar_forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string controlbar_mute {
            get {
                return ResourceManager.GetString("controlbar_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string controlbar_pause {
            get {
                return ResourceManager.GetString("controlbar_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string controlbar_play {
            get {
                return ResourceManager.GetString("controlbar_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string controlbar_repeat {
            get {
                return ResourceManager.GetString("controlbar_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seekbar.
        /// </summary>
        public static string controlbar_seekbar {
            get {
                return ResourceManager.GetString("controlbar_seekbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string controlbar_stop {
            get {
                return ResourceManager.GetString("controlbar_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the begining.
        /// </summary>
        public static string controlbar_to_begining {
            get {
                return ResourceManager.GetString("controlbar_to_begining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the end.
        /// </summary>
        public static string controlbar_to_end {
            get {
                return ResourceManager.GetString("controlbar_to_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string controlbar_volume {
            get {
                return ResourceManager.GetString("controlbar_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, press desired key combination:.
        /// </summary>
        public static string enter_key_message {
            get {
                return ResourceManager.GetString("enter_key_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string failedstreams_caption {
            get {
                return ResourceManager.GetString("failedstreams_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were streams that PVP could not render. The details are listed below..
        /// </summary>
        public static string failedstreams_msg1 {
            get {
                return ResourceManager.GetString("failedstreams_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely the streams were not rendered because necessary decoders are not installed..
        /// </summary>
        public static string failedstreams_msg2 {
            get {
                return ResourceManager.GetString("failedstreams_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .3g2 - 3GPP2.
        /// </summary>
        public static string file_type_3g2 {
            get {
                return ResourceManager.GetString("file_type_3g2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .3gp - 3GPP.
        /// </summary>
        public static string file_type_3gp {
            get {
                return ResourceManager.GetString("file_type_3gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .asf - Advanced Streaming Format.
        /// </summary>
        public static string file_type_asf {
            get {
                return ResourceManager.GetString("file_type_asf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .avi - Audio-Video Interleaved.
        /// </summary>
        public static string file_type_avi {
            get {
                return ResourceManager.GetString("file_type_avi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dat - MPEG movie on VCD or SVCD.
        /// </summary>
        public static string file_type_dat {
            get {
                return ResourceManager.GetString("file_type_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .divx - Avi file compressed with DivX codec.
        /// </summary>
        public static string file_type_divx {
            get {
                return ResourceManager.GetString("file_type_divx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .flv - Flash Video.
        /// </summary>
        public static string file_type_flv {
            get {
                return ResourceManager.GetString("file_type_flv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ifo - DVD file.
        /// </summary>
        public static string file_type_ifo {
            get {
                return ResourceManager.GetString("file_type_ifo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .m1v - MPEG1 video only.
        /// </summary>
        public static string file_type_m1v {
            get {
                return ResourceManager.GetString("file_type_m1v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blu-ray Disc Audio-Video MPEG-2 Transport Stream.
        /// </summary>
        public static string file_type_m2ts {
            get {
                return ResourceManager.GetString("file_type_m2ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .m2v - MPEG2 video only.
        /// </summary>
        public static string file_type_m2v {
            get {
                return ResourceManager.GetString("file_type_m2v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mkv - Matroska video.
        /// </summary>
        public static string file_type_mkv {
            get {
                return ResourceManager.GetString("file_type_mkv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mov - QuickTime movie.
        /// </summary>
        public static string file_type_mov {
            get {
                return ResourceManager.GetString("file_type_mov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mp4 - MPEG4.
        /// </summary>
        public static string file_type_mp4 {
            get {
                return ResourceManager.GetString("file_type_mp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpe - Motion Picture Experts Group.
        /// </summary>
        public static string file_type_mpe {
            get {
                return ResourceManager.GetString("file_type_mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpeg - Motion Picture Experts Group.
        /// </summary>
        public static string file_type_mpeg {
            get {
                return ResourceManager.GetString("file_type_mpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mpg - Motion Picture Experts Group.
        /// </summary>
        public static string file_type_mpg {
            get {
                return ResourceManager.GetString("file_type_mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .qt - QuickTime movie.
        /// </summary>
        public static string file_type_qt {
            get {
                return ResourceManager.GetString("file_type_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vob - Video Object.
        /// </summary>
        public static string file_type_vob {
            get {
                return ResourceManager.GetString("file_type_vob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .wmv - Windows Media Video.
        /// </summary>
        public static string file_type_wmv {
            get {
                return ResourceManager.GetString("file_type_wmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string folder_select_dialog_caption {
            get {
                return ResourceManager.GetString("folder_select_dialog_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        public static string infodialog_Aspect_Ratio {
            get {
                return ResourceManager.GetString("infodialog_Aspect_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Rate.
        /// </summary>
        public static string infodialog_Bit_Rate {
            get {
                return ResourceManager.GetString("infodialog_Bit_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kbit/s.
        /// </summary>
        public static string infodialog_bitrate_value_format {
            get {
                return ResourceManager.GetString("infodialog_bitrate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} bits per sample.
        /// </summary>
        public static string infodialog_bits_per_sample_format {
            get {
                return ResourceManager.GetString("infodialog_bits_per_sample_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string infodialog_caption {
            get {
                return ResourceManager.GetString("infodialog_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} channel.
        /// </summary>
        public static string infodialog_channel_format {
            get {
                return ResourceManager.GetString("infodialog_channel_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} channels.
        /// </summary>
        public static string infodialog_channels_format {
            get {
                return ResourceManager.GetString("infodialog_channels_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Chapter.
        /// </summary>
        public static string infodialog_Current_Chapter {
            get {
                return ResourceManager.GetString("infodialog_Current_Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Domain.
        /// </summary>
        public static string infodialog_Current_Domain {
            get {
                return ResourceManager.GetString("infodialog_Current_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Title.
        /// </summary>
        public static string infodialog_Current_Title {
            get {
                return ResourceManager.GetString("infodialog_Current_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string infodialog_duration {
            get {
                return ResourceManager.GetString("infodialog_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        public static string infodialog_dvd_frequency_value_format {
            get {
                return ResourceManager.GetString("infodialog_dvd_frequency_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstPlay.
        /// </summary>
        public static string infodialog_dvddomain_FirstPlay {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_FirstPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string infodialog_dvddomain_Stop {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string infodialog_dvddomain_Title {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoManagerMenu.
        /// </summary>
        public static string infodialog_dvddomain_VideoManagerMenu {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_VideoManagerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoTitleSetMenu.
        /// </summary>
        public static string infodialog_dvddomain_VideoTitleSetMenu {
            get {
                return ResourceManager.GetString("infodialog_dvddomain_VideoTitleSetMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string infodialog_Format {
            get {
                return ResourceManager.GetString("infodialog_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Type.
        /// </summary>
        public static string infodialog_Format_Type {
            get {
                return ResourceManager.GetString("infodialog_Format_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Rate.
        /// </summary>
        public static string infodialog_Frame_Rate {
            get {
                return ResourceManager.GetString("infodialog_Frame_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f3} Hz.
        /// </summary>
        public static string infodialog_framerate_value_format {
            get {
                return ResourceManager.GetString("infodialog_framerate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlace Mode.
        /// </summary>
        public static string infodialog_Interlace_Mode {
            get {
                return ResourceManager.GetString("infodialog_Interlace_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string infodialog_Language {
            get {
                return ResourceManager.GetString("infodialog_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Source.
        /// </summary>
        public static string infodialog_media_source {
            get {
                return ResourceManager.GetString("infodialog_media_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hz.
        /// </summary>
        public static string infodialog_samplerate_value_format {
            get {
                return ResourceManager.GetString("infodialog_samplerate_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream {0}.
        /// </summary>
        public static string infodialog_Stream_format {
            get {
                return ResourceManager.GetString("infodialog_Stream_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Duration.
        /// </summary>
        public static string infodialog_Title_Duration {
            get {
                return ResourceManager.GetString("infodialog_Title_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV System.
        /// </summary>
        public static string infodialog_TV_System {
            get {
                return ResourceManager.GetString("infodialog_TV_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} Hz.
        /// </summary>
        public static string infodialog_tv_system_value_format {
            get {
                return ResourceManager.GetString("infodialog_tv_system_value_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type/Format.
        /// </summary>
        public static string infodialog_type_format {
            get {
                return ResourceManager.GetString("infodialog_type_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Format.
        /// </summary>
        public static string infodialog_Video_Format {
            get {
                return ResourceManager.GetString("infodialog_Video_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        public static string infodialog_Video_Size {
            get {
                return ResourceManager.GetString("infodialog_Video_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string keys_about {
            get {
                return ResourceManager.GetString("keys_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string keys_app {
            get {
                return ResourceManager.GetString("keys_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:9.
        /// </summary>
        public static string keys_ar_16_9 {
            get {
                return ResourceManager.GetString("keys_ar_16_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4:3.
        /// </summary>
        public static string keys_ar_4_3 {
            get {
                return ResourceManager.GetString("keys_ar_4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 47:20.
        /// </summary>
        public static string keys_ar_47_20 {
            get {
                return ResourceManager.GetString("keys_ar_47_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string keys_ar_free {
            get {
                return ResourceManager.GetString("keys_ar_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Original.
        /// </summary>
        public static string keys_ar_original {
            get {
                return ResourceManager.GetString("keys_ar_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        public static string keys_aspect_ratio {
            get {
                return ResourceManager.GetString("keys_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string keys_backward {
            get {
                return ResourceManager.GetString("keys_backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string keys_close_file {
            get {
                return ResourceManager.GetString("keys_close_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string keys_exit {
            get {
                return ResourceManager.GetString("keys_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string keys_file {
            get {
                return ResourceManager.GetString("keys_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        public static string keys_file_info {
            get {
                return ResourceManager.GetString("keys_file_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string keys_forward {
            get {
                return ResourceManager.GetString("keys_forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string keys_full_screen {
            get {
                return ResourceManager.GetString("keys_full_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string keys_open_file {
            get {
                return ResourceManager.GetString("keys_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Play.
        /// </summary>
        public static string keys_pause {
            get {
                return ResourceManager.GetString("keys_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string keys_play {
            get {
                return ResourceManager.GetString("keys_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string keys_playback {
            get {
                return ResourceManager.GetString("keys_playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string keys_pref {
            get {
                return ResourceManager.GetString("keys_pref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string keys_repeat {
            get {
                return ResourceManager.GetString("keys_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot.
        /// </summary>
        public static string keys_screenshot {
            get {
                return ResourceManager.GetString("keys_screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string keys_seek {
            get {
                return ResourceManager.GetString("keys_seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string keys_stop {
            get {
                return ResourceManager.GetString("keys_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        public static string keys_video_size {
            get {
                return ResourceManager.GetString("keys_video_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        public static string keys_video_size_100 {
            get {
                return ResourceManager.GetString("keys_video_size_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200%.
        /// </summary>
        public static string keys_video_size_200 {
            get {
                return ResourceManager.GetString("keys_video_size_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50%.
        /// </summary>
        public static string keys_video_size_50 {
            get {
                return ResourceManager.GetString("keys_video_size_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string keys_video_size_free {
            get {
                return ResourceManager.GetString("keys_video_size_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string keys_volume {
            get {
                return ResourceManager.GetString("keys_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string keys_volume_decrease {
            get {
                return ResourceManager.GetString("keys_volume_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string keys_volume_increase {
            get {
                return ResourceManager.GetString("keys_volume_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string keys_volume_mute {
            get {
                return ResourceManager.GetString("keys_volume_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string mi_about {
            get {
                return ResourceManager.GetString("mi_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle {0}.
        /// </summary>
        public static string mi_angle_format {
            get {
                return ResourceManager.GetString("mi_angle_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Menu.
        /// </summary>
        public static string mi_angle_menu {
            get {
                return ResourceManager.GetString("mi_angle_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing Angles.
        /// </summary>
        public static string mi_angles {
            get {
                return ResourceManager.GetString("mi_angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string mi_app_lang {
            get {
                return ResourceManager.GetString("mi_app_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string mi_app_lang_default {
            get {
                return ResourceManager.GetString("mi_app_lang_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string mi_app_lang_russian {
            get {
                return ResourceManager.GetString("mi_app_lang_russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string mi_application {
            get {
                return ResourceManager.GetString("mi_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        public static string mi_aspect_ratio {
            get {
                return ResourceManager.GetString("mi_aspect_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string mi_aspect_ratio_free {
            get {
                return ResourceManager.GetString("mi_aspect_ratio_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Original.
        /// </summary>
        public static string mi_aspect_ratio_original {
            get {
                return ResourceManager.GetString("mi_aspect_ratio_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Menu.
        /// </summary>
        public static string mi_audio_menu {
            get {
                return ResourceManager.GetString("mi_audio_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Streams.
        /// </summary>
        public static string mi_audio_streams {
            get {
                return ResourceManager.GetString("mi_audio_streams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter {0}.
        /// </summary>
        public static string mi_chapter_format {
            get {
                return ResourceManager.GetString("mi_chapter_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Menu.
        /// </summary>
        public static string mi_chapter_menu {
            get {
                return ResourceManager.GetString("mi_chapter_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Menu (Resume).
        /// </summary>
        public static string mi_close_menu_resume {
            get {
                return ResourceManager.GetString("mi_close_menu_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Controlbar.
        /// </summary>
        public static string mi_controlbar {
            get {
                return ResourceManager.GetString("mi_controlbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Subtitles.
        /// </summary>
        public static string mi_display_subpictures {
            get {
                return ResourceManager.GetString("mi_display_subpictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string mi_exit {
            get {
                return ResourceManager.GetString("mi_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string mi_file {
            get {
                return ResourceManager.GetString("mi_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lose.
        /// </summary>
        public static string mi_file_close {
            get {
                return ResourceManager.GetString("mi_file_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Information.
        /// </summary>
        public static string mi_file_information {
            get {
                return ResourceManager.GetString("mi_file_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string mi_file_open {
            get {
                return ResourceManager.GetString("mi_file_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play DVD.
        /// </summary>
        public static string mi_file_play_dvd {
            get {
                return ResourceManager.GetString("mi_file_play_dvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string mi_filters {
            get {
                return ResourceManager.GetString("mi_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string mi_fullscreen {
            get {
                return ResourceManager.GetString("mi_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To....
        /// </summary>
        public static string mi_goto_menu {
            get {
                return ResourceManager.GetString("mi_goto_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Languages.
        /// </summary>
        public static string mi_menu_languages {
            get {
                return ResourceManager.GetString("mi_menu_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_ause.
        /// </summary>
        public static string mi_pause {
            get {
                return ResourceManager.GetString("mi_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Play.
        /// </summary>
        public static string mi_play {
            get {
                return ResourceManager.GetString("mi_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playrate.
        /// </summary>
        public static string mi_playrate {
            get {
                return ResourceManager.GetString("mi_playrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string mi_preferences {
            get {
                return ResourceManager.GetString("mi_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string mi_properties {
            get {
                return ResourceManager.GetString("mi_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string mi_repeat {
            get {
                return ResourceManager.GetString("mi_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Menu.
        /// </summary>
        public static string mi_root_menu {
            get {
                return ResourceManager.GetString("mi_root_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Menu.
        /// </summary>
        public static string mi_select_menu {
            get {
                return ResourceManager.GetString("mi_select_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        public static string mi_stop {
            get {
                return ResourceManager.GetString("mi_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subpicture Menu.
        /// </summary>
        public static string mi_subpicture_menu {
            get {
                return ResourceManager.GetString("mi_subpicture_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string mi_subpictures {
            get {
                return ResourceManager.GetString("mi_subpictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title {0}.
        /// </summary>
        public static string mi_title_format {
            get {
                return ResourceManager.GetString("mi_title_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Menu.
        /// </summary>
        public static string mi_title_menu {
            get {
                return ResourceManager.GetString("mi_title_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Size.
        /// </summary>
        public static string mi_video_size {
            get {
                return ResourceManager.GetString("mi_video_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string mi_video_size_free {
            get {
                return ResourceManager.GetString("mi_video_size_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string mi_volume {
            get {
                return ResourceManager.GetString("mi_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string mi_volume_down {
            get {
                return ResourceManager.GetString("mi_volume_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string mi_volume_mute {
            get {
                return ResourceManager.GetString("mi_volume_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string mi_volume_up {
            get {
                return ResourceManager.GetString("mi_volume_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string preferred_filter_auto {
            get {
                return ResourceManager.GetString("preferred_filter_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful and convenient video player for Windows 2000, XP, Vista, 7 and 8. The player is capable to play most video formats (given the necessary decoders are present on the system) and provides full DVD support. In addition, it provides advanced functionality like configuration of preferred decoders and renderers..
        /// </summary>
        public static string program_description {
            get {
                return ResourceManager.GetString("program_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Video Player.
        /// </summary>
        public static string program_name {
            get {
                return ResourceManager.GetString("program_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string settings_caption {
            get {
                return ResourceManager.GetString("settings_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types.
        /// </summary>
        public static string settings_filetypes_caption {
            get {
                return ResourceManager.GetString("settings_filetypes_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string settings_filetypes_clear_all {
            get {
                return ResourceManager.GetString("settings_filetypes_clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file types for which you want Power Video Player to be the default player..
        /// </summary>
        public static string settings_filetypes_description {
            get {
                return ResourceManager.GetString("settings_filetypes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string settings_filetypes_select_all {
            get {
                return ResourceManager.GetString("settings_filetypes_select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically play a loaded file.
        /// </summary>
        public static string settings_general_autoplay {
            get {
                return ResourceManager.GetString("settings_general_autoplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string settings_general_button_choose {
            get {
                return ResourceManager.GetString("settings_general_button_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string settings_general_caption {
            get {
                return ResourceManager.GetString("settings_general_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center window.
        /// </summary>
        public static string settings_general_center_window {
            get {
                return ResourceManager.GetString("settings_general_center_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player options.
        /// </summary>
        public static string settings_general_player_options {
            get {
                return ResourceManager.GetString("settings_general_player_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember volume.
        /// </summary>
        public static string settings_general_remember_volume {
            get {
                return ResourceManager.GetString("settings_general_remember_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots folder.
        /// </summary>
        public static string settings_general_screenshots_folder {
            get {
                return ResourceManager.GetString("settings_general_screenshots_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logo when file is loaded.
        /// </summary>
        public static string settings_general_show_logo {
            get {
                return ResourceManager.GetString("settings_general_show_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in full screen mode.
        /// </summary>
        public static string settings_general_start_fullscreen {
            get {
                return ResourceManager.GetString("settings_general_start_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string settings_general_topmost {
            get {
                return ResourceManager.GetString("settings_general_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string settings_keyboard_about {
            get {
                return ResourceManager.GetString("settings_keyboard_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 16x10.
        /// </summary>
        public static string settings_keyboard_aspectratio16x10 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio16x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 16x9.
        /// </summary>
        public static string settings_keyboard_aspectratio16x9 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio16x9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 1x1.
        /// </summary>
        public static string settings_keyboard_aspectratio1x1 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio1x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 47x20.
        /// </summary>
        public static string settings_keyboard_aspectratio47x20 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio47x20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 4x3.
        /// </summary>
        public static string settings_keyboard_aspectratio4x3 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio4x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: 5x4.
        /// </summary>
        public static string settings_keyboard_aspectratio5x4 {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratio5x4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: Free.
        /// </summary>
        public static string settings_keyboard_aspectratiofree {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratiofree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio: Original.
        /// </summary>
        public static string settings_keyboard_aspectratiooriginal {
            get {
                return ResourceManager.GetString("settings_keyboard_aspectratiooriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        public static string settings_keyboard_back {
            get {
                return ResourceManager.GetString("settings_keyboard_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard/Mouse.
        /// </summary>
        public static string settings_keyboard_caption {
            get {
                return ResourceManager.GetString("settings_keyboard_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string settings_keyboard_clear {
            get {
                return ResourceManager.GetString("settings_keyboard_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string settings_keyboard_clear_all {
            get {
                return ResourceManager.GetString("settings_keyboard_clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close file.
        /// </summary>
        public static string settings_keyboard_close {
            get {
                return ResourceManager.GetString("settings_keyboard_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string settings_keyboard_defaults {
            get {
                return ResourceManager.GetString("settings_keyboard_defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string settings_keyboard_exit {
            get {
                return ResourceManager.GetString("settings_keyboard_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string settings_keyboard_forth {
            get {
                return ResourceManager.GetString("settings_keyboard_forth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string settings_keyboard_fullscreen {
            get {
                return ResourceManager.GetString("settings_keyboard_fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File information.
        /// </summary>
        public static string settings_keyboard_info {
            get {
                return ResourceManager.GetString("settings_keyboard_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Wheel:.
        /// </summary>
        public static string settings_keyboard_mousewheel_action {
            get {
                return ResourceManager.GetString("settings_keyboard_mousewheel_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string settings_keyboard_mute {
            get {
                return ResourceManager.GetString("settings_keyboard_mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string settings_keyboard_open {
            get {
                return ResourceManager.GetString("settings_keyboard_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Play.
        /// </summary>
        public static string settings_keyboard_pause {
            get {
                return ResourceManager.GetString("settings_keyboard_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string settings_keyboard_play {
            get {
                return ResourceManager.GetString("settings_keyboard_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string settings_keyboard_repeat {
            get {
                return ResourceManager.GetString("settings_keyboard_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string settings_keyboard_settings {
            get {
                return ResourceManager.GetString("settings_keyboard_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string settings_keyboard_stop {
            get {
                return ResourceManager.GetString("settings_keyboard_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot.
        /// </summary>
        public static string settings_keyboard_takescreenshot {
            get {
                return ResourceManager.GetString("settings_keyboard_takescreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size: 100%.
        /// </summary>
        public static string settings_keyboard_videosize100 {
            get {
                return ResourceManager.GetString("settings_keyboard_videosize100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size: 200%.
        /// </summary>
        public static string settings_keyboard_videosize200 {
            get {
                return ResourceManager.GetString("settings_keyboard_videosize200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size: 50%.
        /// </summary>
        public static string settings_keyboard_videosize50 {
            get {
                return ResourceManager.GetString("settings_keyboard_videosize50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size: Free.
        /// </summary>
        public static string settings_keyboard_videosizefree {
            get {
                return ResourceManager.GetString("settings_keyboard_videosizefree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        public static string settings_keyboard_volumedown {
            get {
                return ResourceManager.GetString("settings_keyboard_volumedown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string settings_keyboard_volumeup {
            get {
                return ResourceManager.GetString("settings_keyboard_volumeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open Default Programs Panel. Please make sure you have properly registered PVP by launching it from a command prompt with the following parameter: -regapp.
        /// </summary>
        public static string settings_launch_external_ui_error {
            get {
                return ResourceManager.GetString("settings_launch_external_ui_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string settings_mousewheel_action_seek {
            get {
                return ResourceManager.GetString("settings_mousewheel_action_seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound volume.
        /// </summary>
        public static string settings_mousewheel_action_volume {
            get {
                return ResourceManager.GetString("settings_mousewheel_action_volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Default Programs Panel.
        /// </summary>
        public static string settings_show_external_ui_text {
            get {
                return ResourceManager.GetString("settings_show_external_ui_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string settings_video_caption {
            get {
                return ResourceManager.GetString("settings_video_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Video Renderer.
        /// </summary>
        public static string settings_video_evr {
            get {
                return ResourceManager.GetString("settings_video_evr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string settings_video_recommended {
            get {
                return ResourceManager.GetString("settings_video_recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Video Renderer.
        /// </summary>
        public static string settings_video_renderer {
            get {
                return ResourceManager.GetString("settings_video_renderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Mixing Renderer.
        /// </summary>
        public static string settings_video_vmr {
            get {
                return ResourceManager.GetString("settings_video_vmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Mixing Renderer (Windowed).
        /// </summary>
        public static string settings_video_vmr_windowed {
            get {
                return ResourceManager.GetString("settings_video_vmr_windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Mixing Renderer 9.
        /// </summary>
        public static string settings_video_vmr9 {
            get {
                return ResourceManager.GetString("settings_video_vmr9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Mixing Renderer 9 (Windowed).
        /// </summary>
        public static string settings_video_vmr9_windowed {
            get {
                return ResourceManager.GetString("settings_video_vmr9_windowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Renderer.
        /// </summary>
        public static string settings_video_vr {
            get {
                return ResourceManager.GetString("settings_video_vr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have altered the &quot;System Tray&quot; option.{0}You need to restart the application for the changes to take effect..
        /// </summary>
        public static string systray_warning_format {
            get {
                return ResourceManager.GetString("systray_warning_format", resourceCulture);
            }
        }
    }
}
